<a href="https://colab.research.google.com/github/elizamelo/LabFis04/blob/main/LabFis4Interferencia_Turma02_2023_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

Laboratório de Física IV 
Prática 05 : Interferência



Grupo 01: D=2700 (mm); n_i=5; Y_A= 35,Y_B= 17,Y_C=26,Y_D=16 (mm);lambda_L_R = 632.8 (nm)

Grupo 02: D=2720 (mm); n_i=5; Y_A= 17,Y_B= 33,Y_C=16.5,Y_D=34 (mm);lambda_L_R = 632.8 (nm)

Grupo 03: D=2762 (mm); n_A=5; n_B=5;n_C=4;n_D=5; Y_A: 36.0 ;Y_B: 16.0 ;Y_C: 28.0 ;Y_D: 17.0 (mm);




# Grupo 01 - Giulia,Juliana, Luiz e Tadeu





In [124]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2700 # mm

In [125]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [126]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 5 ;n_D: 5 .


In [127]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 35.0
Y_B= 17.0
Y_C= 26.0
Y_D= 16.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 35.0 ;Y_B: 17.0 ;Y_C: 26.0 ;Y_D: 16.0 .


In [128]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 7.0 ;Dy_B: 3.4 ;Dy_C: 5.2 ;Dy_D: 3.2 .


In [129]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D) 
l_B= (d_B*Dy_B/D) 
l_C= (d_C*Dy_C/D) 
l_D= (d_D*Dy_D/D) 
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0006481481481481481 ;l_B: 0.0006296296296296296 ;l_C: 0.0004814814814814815 ;l_D: 0.0005925925925925926 .


In [130]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 648.1481481481482 (nm);l_B: 629.6296296296296 (nm);l_C: 481.4814814814815 (nm);l_D: 592.5925925925926 (nm).


In [131]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([648.14814815, 629.62962963, 481.48148148, 592.59259259])

In [132]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) ) 

Média (mm) = 587.962962962963
Variância populacional (mm²) = 4179.526748971082


Desvio padrão populacional:


In [133]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 64.64925946189238


In [134]:
np.std( array_L, ddof=1 )

74.65053470646802

Desvio padrão amostral:


In [135]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 74.65053470646706


In [136]:
np.std( array_L, ddof=1 )

74.65053470646802

Erro da média:

In [137]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 37.32526735323353


In [138]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 37.32526735323353


Estimativa do comprimento de onda da fonte:


In [139]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 587.96 ± 37.33 (nm)


Discrepância: L_ref=632.8nm

In [140]:
l = media_L 
l


587.962962962963

In [141]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [142]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

1.2

In [143]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")  

Compatível


#Grupo 02 - Denilson,Giovana,Guilherme,Gustavo

In [144]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2720# mm

In [145]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [146]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 5 ;n_D: 5 .


In [147]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 17.0
Y_B= 33.0
Y_C= 16.5
Y_D= 34.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 17.0 ;Y_B: 33.0 ;Y_C: 16.5 ;Y_D: 34.0 .


In [148]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 3.4 ;Dy_B: 6.6 ;Dy_C: 3.3 ;Dy_D: 6.8 .


In [149]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D) 
l_B= (d_B*Dy_B/D) 
l_C= (d_C*Dy_C/D) 
l_D= (d_D*Dy_D/D) 
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0003125 ;l_B: 0.001213235294117647 ;l_C: 0.00030330882352941173 ;l_D: 0.00125 .


In [150]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 312.5 (nm);l_B: 1213.2352941176468 (nm);l_C: 303.3088235294117 (nm);l_D: 1250.0 (nm).


In [151]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([ 312.5       , 1213.23529412,  303.30882353, 1250.        ])

In [152]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) ) 

Média (mm) = 769.7610294117646
Variância populacional (mm²) = 213491.05042982264


Desvio padrão populacional:


In [153]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 462.0509175727526


In [154]:
np.std( array_L, ddof=0 )

462.0509175727526

Desvio padrão amostral:


In [155]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 533.5304432798846


In [156]:
np.std( array_L, ddof=1 )

533.5304432798846

Erro da média:

In [157]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 266.7652216399423


In [158]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 266.7652216399423


Estimativa do comprimento de onda da fonte:


In [159]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 769.76 ± 266.77 (nm)


Discrepância: L_ref=632.8nm

In [160]:
l = media_L 
l


769.7610294117646

In [161]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [162]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

0.51

In [163]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")  

Compatível


#Grupo 03 -  Paloma




Grupo 03: D=2762 (mm); n_A=5; n_B=5;n_C=4;n_D=5; Y_A: 36.0 ;Y_B: 16.0 ;Y_C: 28.0 ;Y_D: 17.0  (mm);




In [164]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2762# mm

In [165]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [166]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 4
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 4 ;n_D: 5 .


In [167]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 36.0
Y_B= 16.0
Y_C= 28.0
Y_D= 17.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 36.0 ;Y_B: 16.0 ;Y_C: 28.0 ;Y_D: 17.0 .


In [168]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 7.2 ;Dy_B: 3.2 ;Dy_C: 7.0 ;Dy_D: 3.4 .


In [169]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D) 
l_B= (d_B*Dy_B/D) 
l_C= (d_C*Dy_C/D) 
l_D= (d_D*Dy_D/D) 
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0006517016654598118 ;l_B: 0.0005792903692976105 ;l_C: 0.0006335988414192614 ;l_D: 0.0006154960173787111 .


In [170]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 651.7016654598118 (nm);l_B: 579.2903692976105 (nm);l_C: 633.5988414192614 (nm);l_D: 615.4960173787111 (nm).


In [171]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([651.70166546, 579.2903693 , 633.59884142, 615.49601738])

In [172]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) ) 

Média (mm) = 620.0217233888487
Variância populacional (mm²) = 716.8705211568158


Desvio padrão populacional:


In [173]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 26.774437830826923


In [174]:
np.std( array_L, ddof=1 )

30.916457778058156

Desvio padrão amostral:


In [175]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 30.916457778057644


In [176]:
np.std( array_L, ddof=1 )

30.916457778058156

Erro da média:

In [177]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 15.458228889028822


In [178]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 15.458228889028822


Estimativa do comprimento de onda da fonte:


In [179]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 620.02 ± 15.46 (nm)


Discrepância: L_ref=632.8nm

In [180]:
l = media_L 
l


620.0217233888487

In [181]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [182]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

0.83

In [183]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")  

Compatível
