<a href="https://colab.research.google.com/github/elizamelo/LabFis04/blob/main/Turma08/LabFis4Interferencia_Turma08_2023_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

Laboratório de Física IV
Prática 05 : Interferência



Grupo 01: D=2080 (mm); n_i=5; Y_A= 25,Y_B= 12,Y_C=25,Y_D=10 (mm);lambda_L_R = 632.8 (nm)

Grupo 02: D=2700 (mm); n_i=5; Y_A= 26,Y_B= 14,Y_C=27,Y_D=13 (mm);lambda_L_R = 632.8 (nm)

Grupo 03: D=2705(mm); n_A=5; n_B=6;n_C=4;n_D=5; Y_A: 34.0 ;Y_B: 20.0 ;Y_C: 35.0 ;Y_D: 17.0 (mm);




# Grupo 03 - Cleber e Mateus





In [63]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2705 # mm

In [64]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [65]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 6
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 6 ;n_C: 5 ;n_D: 5 .


In [66]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 34.0
Y_B= 20.0
Y_C= 35.0
Y_D= 17.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 34.0 ;Y_B: 20.0 ;Y_C: 35.0 ;Y_D: 17.0 .


In [67]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 6.8 ;Dy_B: 3.3333333333333335 ;Dy_C: 7.0 ;Dy_D: 3.4 .


In [68]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0006284658040665434 ;l_B: 0.0006161429451632779 ;l_C: 0.0006469500924214418 ;l_D: 0.0006284658040665434 .


In [69]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 628.4658040665435 (nm);l_B: 616.1429451632779 (nm);l_C: 646.9500924214418 (nm);l_D: 628.4658040665435 (nm).


In [70]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([628.46580407, 616.14294516, 646.95009242, 628.46580407])

In [71]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 630.0061614294517
Variância populacional (mm²) = 121.00774107867619


Desvio padrão populacional:


In [72]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 11.000351861584983


In [73]:
np.std( array_L, ddof=1 )

12.702112216936737

Desvio padrão amostral:


In [74]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 12.702112216933381


In [75]:
np.std( array_L, ddof=1 )

12.702112216936737

Erro da média:

In [76]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 6.3510561084666906


In [77]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 6.3510561084666906


Estimativa do comprimento de onda da fonte:


In [78]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 630.01 ± 6.35 (nm)


Discrepância: L_ref=632.8nm

In [79]:
l = media_L
l


630.0061614294517

In [80]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [81]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

0.44

In [82]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Compatível


#Grupo 02 - Mariana Pimenta e Brendon


In [83]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2700# mm

In [84]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [85]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 5 ;n_D: 5 .


In [86]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 26.0
Y_B= 14.0
Y_C= 27.0
Y_D= 13.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 26.0 ;Y_B: 14.0 ;Y_C: 27.0 ;Y_D: 13.0 .


In [87]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 5.2 ;Dy_B: 2.8 ;Dy_C: 5.4 ;Dy_D: 2.6 .


In [88]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0004814814814814815 ;l_B: 0.0005185185185185185 ;l_C: 0.0005 ;l_D: 0.0004814814814814815 .


In [89]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 481.4814814814815 (nm);l_B: 518.5185185185185 (nm);l_C: 500.0 (nm);l_D: 481.4814814814815 (nm).


In [90]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([481.48148148, 518.51851852, 500.        , 481.48148148])

In [91]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 495.3703703703704
Variância populacional (mm²) = 235.76817558301263


Desvio padrão populacional:


In [92]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 15.354744399794242


In [93]:
np.std( array_L, ddof=0 )

15.354744399793484

Desvio padrão amostral:


In [94]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 17.730131625118208


In [95]:
np.std( array_L, ddof=1 )

17.730131625117334

Erro da média:

In [96]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 8.865065812559104


In [97]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 8.865065812559104


Estimativa do comprimento de onda da fonte:


In [98]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 495.37 ± 8.87 (nm)


Discrepância: L_ref=632.8nm

In [99]:
l = media_L
l


495.3703703703704

In [100]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [101]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

15.5

In [102]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Incompatível


#Grupo 01 -  Heitor, Christian e Renan




Grupo 03: D=2080 (mm); n_A=5; n_B=5;n_C=4;n_D=5; Y_A: 25.0 ;Y_B: 12.0 ;Y_C: 25.0 ;Y_D: 10.0  (mm);




In [103]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2080# mm

In [104]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [105]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 5 ;n_D: 5 .


In [106]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 25.0
Y_B= 12.0
Y_C= 25.0
Y_D= 10.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 25.0 ;Y_B: 12.0 ;Y_C: 25.0 ;Y_D: 10.0 .


In [107]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 5.0 ;Dy_B: 2.4 ;Dy_C: 5.0 ;Dy_D: 2.0 .


In [108]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0006009615384615385 ;l_B: 0.0005769230769230769 ;l_C: 0.0006009615384615385 ;l_D: 0.0004807692307692308 .


In [109]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 600.9615384615385 (nm);l_B: 576.9230769230769 (nm);l_C: 600.9615384615385 (nm);l_D: 480.7692307692308 (nm).


In [110]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([600.96153846, 576.92307692, 600.96153846, 480.76923077])

In [111]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 564.9038461538462
Variância populacional (mm²) = 2455.852440828341


Desvio padrão populacional:


In [112]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 49.556558000211645


In [113]:
np.std( array_L, ddof=1 )

57.2229842030677

Desvio padrão amostral:


In [114]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 57.222984203066986


In [115]:
np.std( array_L, ddof=1 )

57.2229842030677

Erro da média:

In [116]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 28.611492101533493


In [117]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 28.611492101533496


Estimativa do comprimento de onda da fonte:


In [118]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 564.90 ± 28.61 (nm)


Discrepância: L_ref=632.8nm

In [119]:
l = media_L
l


564.9038461538462

In [120]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [121]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

2.37

In [122]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Incompatível
