<a href="https://colab.research.google.com/github/elizamelo/LabFis04/blob/main/2024_01/LabFis4Interferencia_Turma0106_2024_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

Laboratório de Física IV
Prática 05 : Interferência



Grupo 01: D=2700 (mm); n_i=5; Y_A= 35,Y_B= 17,Y_C=26,Y_D=16 (mm);lambda_L_R = 632.8 (nm)

Grupo 02: D=2720 (mm); n_i=5; Y_A= 17,Y_B= 33,Y_C=16.5,Y_D=34 (mm);lambda_L_R = 632.8 (nm)

Grupo 03: D=2762 (mm); n_A=5; n_B=5;n_C=4;n_D=5; Y_A: 36.0 ;Y_B: 16.0 ;Y_C: 28.0 ;Y_D: 17.0 (mm);




# Grupo 01 -




In [2]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 1900 # mm

In [3]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [4]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 4
n_B = 4
n_C = 5
n_D = 4
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 4 ;n_B: 4 ;n_C: 5 ;n_D: 4 .


In [5]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 19.0
Y_B= 9.0
Y_C= 24.0
Y_D= 12.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 19.0 ;Y_B: 9.0 ;Y_C: 24.0 ;Y_D: 12.0 .


In [6]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 4.75 ;Dy_B: 2.25 ;Dy_C: 4.8 ;Dy_D: 3.0 .


In [7]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.000625 ;l_B: 0.0005921052631578948 ;l_C: 0.0006315789473684211 ;l_D: 0.0007894736842105263 .


In [8]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 625.0 (nm);l_B: 592.1052631578948 (nm);l_C: 631.578947368421 (nm);l_D: 789.4736842105262 (nm).


In [9]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([625.        , 592.10526316, 631.57894737, 789.47368421])

In [10]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 659.5394736842105
Variância populacional (mm²) = 5851.259522160748


Desvio padrão populacional:


In [11]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 76.49352601469452


In [12]:
np.std( array_L, ddof=1 )

88.32711567169437

Desvio padrão amostral:


In [13]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 88.32711567169504


In [14]:
np.std( array_L, ddof=1 )

88.32711567169437

Erro da média:

In [15]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 44.16355783584752


In [16]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 44.16355783584753


Estimativa do comprimento de onda da fonte:


In [17]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 659.54 ± 44.16 (nm)


Discrepância: L_ref=632.8nm

In [18]:
l = media_L
l


659.5394736842105

In [19]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [20]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

0.61

In [21]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Compatível


#Grupo 03 -

In [22]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 2080# mm

In [23]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [24]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 7
n_C = 4
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 7 ;n_C: 4 ;n_D: 5 .


In [25]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 27.0
Y_B= 17.0
Y_C= 20.0
Y_D= 13.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 27.0 ;Y_B: 17.0 ;Y_C: 20.0 ;Y_D: 13.0 .


In [26]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 5.4 ;Dy_B: 2.4285714285714284 ;Dy_C: 5.0 ;Dy_D: 2.6 .


In [27]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0006490384615384615 ;l_B: 0.0005837912087912088 ;l_C: 0.0006009615384615385 ;l_D: 0.000625 .


In [28]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 649.0384615384615 (nm);l_B: 583.7912087912088 (nm);l_C: 600.9615384615385 (nm);l_D: 625.0 (nm).


In [29]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([649.03846154, 583.79120879, 600.96153846, 625.        ])

In [30]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 614.6978021978022
Variância populacional (mm²) = 607.3296552348766


Desvio padrão populacional:


In [31]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 24.644059228034585


In [32]:
np.std( array_L, ddof=0 )

24.644059228034568

Desvio padrão amostral:


In [33]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 28.456508458461695


In [34]:
np.std( array_L, ddof=1 )

28.456508458461677

Erro da média:

In [35]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 14.228254229230847


In [36]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 14.228254229230847


Estimativa do comprimento de onda da fonte:


In [37]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 614.70 ± 14.23 (nm)


Discrepância: L_ref=632.8nm

In [38]:
l = media_L
l


614.6978021978022

In [39]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [40]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

1.27

In [41]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Compatível


#Grupo 02 turma 6 - Caio, João e Patricia  


In [42]:
#Dinstância entre as fendas e a folha de observação D(mm):

D = 1815# mm

In [43]:
#Dinstância entre as fendas "d"(mm):
d_A = 0.250
d_B = 0.500
d_C = 0.250
d_D = 0.500


In [44]:
#Número de configurões da Lâmina "N":
#N = 4
#Número de intervalos de Máximos :
n_A = 5
n_B = 5
n_C = 5
n_D = 5
print("n_A:", n_A,";""n_B:", n_B,";""n_C:", n_C,";""n_D:", n_D,".")

n_A: 5 ;n_B: 5 ;n_C: 5 ;n_D: 5 .


In [45]:
#Distâncias entre máximos medidos com a régua para cada Configuração (mm):
Y_A= 19.0
Y_B= 10.0
Y_C= 17.5
Y_D= 11.0
print("Y_A:", Y_A,";""Y_B:", Y_B,";""Y_C:", Y_C,";""Y_D:", Y_D,".")

Y_A: 19.0 ;Y_B: 10.0 ;Y_C: 17.5 ;Y_D: 11.0 .


In [46]:
#Deta_Y para cada Configuração (mm):
Dy_A= Y_A/n_A
Dy_B= Y_B/n_B
Dy_C= Y_C/n_C
Dy_D= Y_D/n_D
print("Dy_A:", Dy_A,";""Dy_B:", Dy_B,";""Dy_C:", Dy_C,";""Dy_D:", Dy_D,".")

Dy_A: 3.8 ;Dy_B: 2.0 ;Dy_C: 3.5 ;Dy_D: 2.2 .


In [47]:
#Lambda para cada configuração (nm)

l_A= (d_A*Dy_A/D)
l_B= (d_B*Dy_B/D)
l_C= (d_C*Dy_C/D)
l_D= (d_D*Dy_D/D)
print("l_A:", l_A,";""l_B:", l_B,";""l_C:", l_C,";""l_D:", l_D,".")

l_A: 0.0005234159779614325 ;l_B: 0.0005509641873278236 ;l_C: 0.00048209366391184575 ;l_D: 0.0006060606060606061 .


In [48]:
#Passar para nm
print("l_A:", l_A*1e6,"(nm);""l_B:", l_B*1e6,"(nm);""l_C:", l_C*1e6,"(nm);""l_D:", l_D*1e6,"(nm).")

l_A: 523.4159779614325 (nm);l_B: 550.9641873278237 (nm);l_C: 482.09366391184574 (nm);l_D: 606.060606060606 (nm).


In [49]:
array_L = np.array( [ l_A*1e6, l_B*1e6 , l_C*1e6 , l_D*1e6])


array_L

array([523.41597796, 550.96418733, 482.09366391, 606.06060606])

In [50]:
media_L = np.mean( array_L )
print ( "Média (mm) = {}".format( media_L ) )
var_L_p = np.mean( array_L ** 2 ) - np.mean( array_L ) ** 2
print ( "Variância populacional (mm²) = {}".format( var_L_p ) )

Média (mm) = 540.633608815427
Variância populacional (mm²) = 2027.696195615048


Desvio padrão populacional:


In [51]:
sigma_L_p = np.sqrt( var_L_p )
print ( "Desvio padrão populacional (nm) = {}".format( sigma_L_p ) )

Desvio padrão populacional (nm) = 45.02994776384987


In [52]:
np.std( array_L, ddof=1 )

51.99610492610706

Desvio padrão amostral:


In [53]:
N = array_L.size # tamanho da sequência L
print ( "N = {}".format( N ) )

sigma_L_a = np.sqrt( N / (N - 1) ) * sigma_L_p

print ( "Desvio padrão amostral (nm) = {}".format( sigma_L_a ) )

N = 4
Desvio padrão amostral (nm) = 51.996104926107016


In [54]:
np.std( array_L, ddof=1 )

51.99610492610706

Erro da média:

In [55]:
erro_media_L = sigma_L_a / np.sqrt( N )
print ( "Erro da média (nm) = {}".format( erro_media_L ) )

Erro da média (nm) = 25.998052463053508


In [56]:
epsilon_media_L = np.sqrt( var_L_p/(N-1) )
print ( "Erro da média (nm) = {}".format( epsilon_media_L ) )

Erro da média (nm) = 25.99805246305351


Estimativa do comprimento de onda da fonte:


In [57]:
print ( "L = {:.2f} ± {:.2f} (nm)".format( np.round( media_L, 2), np.round( erro_media_L, 2 ) ) )

L = 540.63 ± 26.00 (nm)


Discrepância: L_ref=632.8nm

In [58]:
l = media_L
l


540.633608815427

In [59]:
#Comprimento de onda da fonte laser
lambda_L_R = 632.8 # nm


In [60]:
dis = abs( media_L-(lambda_L_R))/erro_media_L
np.round(dis,2)

3.55

In [61]:
if dis < 2.0:
  print("Compatível")
else:
  print("Incompatível")

Incompatível
